### ISSUE TITLE
doesn't work overrides options

### ISSUE THREAD

**Issue by tgfjt** [sindresorhus/gulp-xo#10]
Hi. thank you for your helpful plugin 😄 

`npm run xo`: overrides works fine.
`gulp xo`:  ignores overrides options.

I wonder that `xo.lintText` doesn't care overrides's files
https://github.com/sindresorhus/xo/blob/master/index.js#L7

```json
{
  "scripts": {
    "xo": "xo src/**/*.js",
  },
  "xo": {
    "extends": "xo-react",
    "plugins": [
      "react"
    ],
    "overrides": [
      {
        "files": "src/Components/**/*.js",
        "rules": {
          "xo/filename-case": [
            "error",
            {
              "case": "pascalCase"
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/xo/commit/040d8be1467d824ec1ca64d2c80a9173c303b73f.

**Comment by tgfjt** [comment]
Great, Thank you very much! 🌟
