### ISSUE TITLE
Failed to load config "xo/esnext" to extend from.

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [sindresorhus/gulp-xo#22]
`> gulp xo`

```
[08:28:52] Using gulpfile ~/git/whmcs-ispapi-domainchecker/gulpfile.js
[08:28:52] Starting 'xo'...
[08:28:52] 'xo' errored after 46 ms
[08:28:52] Error in plugin "gulp-xo"
Message:
    Failed to load config "xo/esnext" to extend from.
Referenced from: BaseConfig
Details:
    messageTemplate: extend-config-missing
    messageData: [object Object]
    fileName: /home/ad.ks.de/kschwarz/git/whmcs-ispapi-domainchecker/gulpfile.js
    domainEmitter: [object Object]
    domainThrown: false
```

where `> npx xo` works just perfectly fine.

reproduce by
```
git clone https://github.com/hexonet/whmcs-ispapi-domainchecker.git
npm i
gulp xo
```

Gulp's xo task: https://github.com/hexonet/whmcs-ispapi-domainchecker/blob/master/gulpfile.js#L43-L48
NOTE: I also tried providing a configuration to xo in the task, which did not improve the situation.

xo's configuration: https://github.com/hexonet/whmcs-ispapi-domainchecker/blob/master/package.json#L42-L54
NOTE: I had this also separated as configuration file, which did not improve the situation.

xo works fine with prettier together, just no idea why gulp-xo runs into trouble. thanks for your help, very appreciated.

**Comment by sindresorhus** [comment]
Make sure you install with the latest version of `npm`. There are some dependency resolution problems in npm 6. Other than that, I would strongly recommend just using the XO binary instead.

**Comment by KaiSchwarz-cnic** [comment]
```
> npm --version
7.21.1
```

**Comment by sindresorhus** [comment]
Then I don't really know... The ESLint rule resolution thing is really broken and I don't know how to fix it. ESLint is planning to replace the config stuff with something simpler (flat config), so I'm hoping that will eventually fix all the weird problems.

For now, I would recommend just using the binary. If you really want it in your Gulp file, you could use https://github.com/robrich/gulp-exec

**Comment by sindresorhus** [comment]
This package is deprecated.
