### ISSUE TITLE
Vulnerability with dependency "got"

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [sindresorhus/gulp-xo#23]
![image](https://user-images.githubusercontent.com/229425/175888413-2c604bb0-9b17-4f79-8cac-d6b2293bba51.png)

`npm ls got` shows
![image](https://user-images.githubusercontent.com/229425/175894271-d3265ca8-b622-4172-af8e-f8bde48d8a19.png)

... so it is probably just about upgrading ava.

**Comment by sindresorhus** [comment]
AVA is a dev dependency, so it is not installed when you install `gulp-xo`, so this report is invalid. You should report this bug to GitHub. They should not report for transitive dev dependencies.

**Comment by KaiSchwarz-cnic** [comment]
@sindresorhus, I am aware of Ava being a devDependency. Still, the report is imho valid. gulp-xo is getting used in our release process, so not in NODE_ENV = production, which is the nature of CI. npm is then installing all modules with all dependencies (including devDependencies) and this dependency tree is then saved as package-lock.json and reused via `npm ci`. Therefore, totally fine how Github is taking it.

**Comment by sindresorhus** [comment]
That's not how it works. Dev dependencies are only installed when you run `npm install` in the package directory, not when you install a dependency. Just try: `npm install gulp-xo` in a new directory and you will not find `ava` there.

**Comment by KaiSchwarz-cnic** [comment]
Seriously?

Execute `npm audit` right after `npm install gulp-xo` and you're getting vulnerabilities shown up.

The case with your module reproducible in my module.
```
git clone https://github.com/hexonet/whmcs-ispapi-domainchecker
npm i
npm audit
```

From technical perspective I at least agree that with our repository we are of course not interested at all in your dev deps. But fact is that your ava is part of our package-lock.json finally and reported as vulnerability. I don't want to start a discussion about that npm could be generating the dependency tree incorrectly in package-lock.json. They keep it that way for a certain reason and in ci when using `npm ci` instead of `npm i` it will rely on the package-lock.json's pre-calculated dependency tree.

Probably the better idea to discontinue with gulp-xo then as you already suggested in my previous gh issue.

**Comment by KaiSchwarz-cnic** [comment]
I "fixed" it now by hardly overriding the dependency's version using package.json overrides.
Leaving people a work around until such issues got patched or a replacement has been identified and rolled out.

```json
	"overrides":{
		"got": "^11.8.2"
	},
```
