### ISSUE TITLE
Compact output

### ISSUE THREAD

**Issue by thasmo** [sindresorhus/gulp-xo#4]
`xo` provides a `compact` option when running on the CLI. Is it possible to use the compact output for `gulp-xo` somehow, as an option maybe?

**Comment by thasmo** [comment]
Some context. I'd love to have `gulp-xo` print out an error per line in the terminal, without header and footer.

**Comment by sindresorhus** [comment]
I decided to add a `reporter` option instead. More flexible. Planning to do the same in XO soon.

**Comment by thasmo** [comment]
Awesome, thanks for the fast reaction! :+1:
