### ISSUE TITLE
While using spaces:true , Expected indentation of 1 tab character but found 0. 

### ISSUE THREAD

**Issue by tarungarg546** [sindresorhus/gulp-xo#6]
Hi,

I am using `gulp-xo` with following code in my `gulpfile.js`

```js
gulp.task('xo', function () {
  return gulp.src('*.js')
              .pipe(xo({
                spaces: true
              }));
});
```

Since i have set spaces:true it should set indentation to 2 spaces for checking but when i run this task it throws errors that it expected 1 tab but found 0. as below :-

![image](https://cloud.githubusercontent.com/assets/10435209/16130512/1b0908ea-3427-11e6-86b4-92ea2cc3c81a.png)

**Comment by sindresorhus** [comment]
Please read the documentation. You don't specify those options in package.json.
