### ISSUE TITLE
Continue checking files if one fails

### ISSUE THREAD

**Issue by bencevans** [sindresorhus/gulp-xo#7]
Hi

I've got the following lint task in my gulp file:

```js
gulp.task('lint', function () {
  return gulp.src(['./*.js', '!./bundle.js', './scripts/utils/**.js'])
    .pipe(xo())
    .pipe(gulp.dest('dest'));
});
```

However if there's lint errors on `app.js` it quits after reporting the error and doesn't continue to report issues with other files e.g `index.js`, `gulpfile.js`. Is there a way around it?

Thanks

Ben

**Comment by kevva** [comment]
Try using https://github.com/floatdrop/gulp-plumber.

**Comment by sindresorhus** [comment]
@kevva I actually implemented this incorrectly initially.

It should only report and fail after having run through all the files, since that's how the CLI works. Shouldn't be to hard to gather up the results for each file and report in the `through2` flush function. PR welcome.
