### ISSUE TITLE
Ignores fail when used in a subdirectory

### ISSUE THREAD

**Issue by chbachman** [sindresorhus/gulp-xo#9]
First of all, thanks for all your hard work on this! I really appreciate it. 
I'm having a problem where gulp-xo seems to fail when dealing with ignores that have a subfolder. 
Example: 

``` json
//Doesn't work.
"ignores": [
  "src/vendor/**"
]
//Works.
"ignores": [
  "vendor/**"
]
```

[The regular xo tool works fine, ignoring the files and continuing on. ](https://cloud.githubusercontent.com/assets/6267043/18460647/d4ace55e-7938-11e6-8147-a376557d77b1.png)
[On the other hand, the gulp-xo tool will still check these files. ](https://cloud.githubusercontent.com/assets/6267043/18460648/d4acde56-7938-11e6-91c3-540102ace300.png)

Those pictures were both taken, one after the other, in the same development enviroment.

Gulpfile:

``` js
const gulp = require('gulp');
const xo = require('gulp-xo');

gulp.task('xo', function () {
    return gulp.src('src/**/*.js')
    .pipe(xo())
    .pipe(gulp.dest('.tmp'));
});
```

package.json:

``` json
"xo": {
    "envs": [
      "browser"
    ],
    "globals": [
      "angular",
      "_"
    ],
    "ignores": [
      "gulp_tasks/**",
      "conf/**",
      "src/vendor/**"
    ]
  }
```

I'm sorry if I missed something obvious about gulp-xo and the difference from xo.

Thanks for your work on this project and other projects.

**Comment by gucong3000** [comment]
```js
return gulp.src('src/**/*.js', {
    base: process.cwd(),
})
  .pipe(xo())
  .pipe(gulp.dest('.tmp'));
```
you can have a try.
